# Site settings
baseURL = "https://othmanbensouda.netlify.app/"
languageCode = "en-us"
title = "othmanbensouda"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""


[params]


  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""
  

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Home"
      url = ""

      
  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Othman Bensouda"
    subtitle = "Harnessing Data & AI to drive Innovation in Education"
    buttonText = "Get Started"


  [[params.banner.social]]
  label = "GitHub"
  url = "https://github.com/yourusername"
  
  [[params.banner.social]]
  label = "LinkedIn"
  url = "https://www.linkedin.com/in/yourprofile"
  
  [[params.banner.social]]
  label = "Email"
  url = "mailto:youremail@example.com"



  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    

    [[params.tiles.showcase]]
      title = "Rescuing At-Risk Students in Morocco"      
      subtitle = "Implementing a Dropout Early Warning System with Machine Learning"
      image = "moroccan_kids.png"
      url = "blogs/dropout"

    [[params.tiles.showcase]]
      title = "Automated Essay Grading Using Transformer Models"      
      subtitle = "Leveraging state-of-the-art transformer models to assess essay quality"
      image = "transformers.jpg"
      url = ""

    [[params.tiles.showcase]]
      title = "Predicting Asset Ownership in Africa Using Satellite Imagery"      
      subtitle = "Leveraging ResNet-18 and Landsat-8 Data for Wealth Index Predictions across 24 Countries"
      image = "africa.jpg"
      url = ""

    [[params.tiles.showcase]]
      title = "Investigating the Impact of Variables on Deep Knowledge Tracing"      
      subtitle = "Improving Student Knowledge Prediction with Additional Features"
      image = "dkt.jpg"
      url = ""
      
      [[params.tiles.showcase]]
      title = "AgeCap: Instant Health Insurance Quote Generator"      
      subtitle = "Instant Health Insurance Quotes with AI Chatbot (RAG) and Automated Emails"
      image = "agescreen.png"
      url = ""
      
      [[params.tiles.showcase]]
      title = "Opticash: Optimized Cash Transfer with Linear Programming"      
      subtitle = "Maximizing Cash Efficiency through Automated Optimization"
      image = "trucks.jpeg"
      url = ""

      [[params.tiles.showcase]]
      title = "Spotify Analysis: Trends and Insights"      
      subtitle = "Leveraging Data to Understand Listener Behavior"
      image = "spotify.png"
      url = ""
      
      [[params.tiles.showcase]]
      title = "Advanced Chatbot Development"      
      subtitle = "Automating Conversations with NLP and Machine Learning"
      image = "chatbot.png"
      url = ""

      [[params.tiles.showcase]]
      title = "OilX : Refinery Event Monitoring System"      
      subtitle = "Real-Time Insights into Global Refinery Disruptions"
      image = "oilx.jpg"
      url = ""
 
      [[params.tiles.showcase]]
      title = "London House Price Estimation Engine"      
      subtitle = "Optimizing Investment Decisions with Machine Learning"
      image = "housepricing.png"
      url = ""


[params.header]
  [[params.header.social]]
    icon = "fab fa-github"  # FontAwesome class for GitHub icon
    url = "https://github.com/OthmanBensoudaKoraichi"
    label = "GitHub"

  [[params.header.social]]
    icon = "fab fa-linkedin"  # FontAwesome class for LinkedIn icon
    url = "https://www.linkedin.com/in/othman-bensouda-koraichi-715330131/"
    label = "LinkedIn"


  [[params.header.social]]
    icon = "fas fa-envelope"  # FontAwesome class for Email icon
    url = "mailto:othmanb@stanford.edu"
    label = "Email"
      

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

